spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-host:3306/db_name
    username: your-username
    password: your-password
  task:
    scheduling:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

data:
  origin: http://tic-tac-toe-4124.s3-website.ap-south-1.amazonaws.com
